### ISSUE TITLE
Filter GitHub commands by repository.

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/SquadBot#5]
The lists of issues, pull requests, and such can get very large.  We should filter results based on repository.  In addition, we can add a !repos command to list all the repositories.

Filters can come in two formats: csegames/cu-core  or cu-core which would show items for both cumosquad and csegames repositories.

ie:

!issues cu-core
!prs cu-core

**Comment by sysrage** [comment]
Should be able to add this easily. Let me know if you want me to stop showing the full list if no parameters are supplied. If you want to prevent that long spam, I can just have it spit out help text saying a repo name needs to be supplied.

**Comment by codecorsair** [comment]
I would say display the top 5 most recent and a short line of text saying for more details pass a repository name to the command.

**Comment by sysrage** [comment]
This is complete.
