### ISSUE TITLE
!printHistory

### ISSUE THREAD

**Issue by syc0n** [CUModSquad/SquadBot#7]
Log all conversation done in modsquad and send it to the requestor.

example:
!printHistory 4h
!printHistory 1h 
!printHistory csejb 1h -n10 (option for filtering by name + n lines above and below the name appeared)

**Comment by sysrage** [comment]
Starting work on this now.

**Comment by sysrage** [comment]
This log functionality has been added as the !chatlog command. If filtering by name is really necessary, please open a separate issue and I'll add that at a later date.
