### ISSUE TITLE
whois

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/SquadBot#8]
I would like to see a !whois feature that will associate Mod Squad users with their CSE / GitHub / Trello usernames.

I have a list of all of these for the initial seed.  Though for adding new members to ModSquad, if there can be a !registeruser <csename> <githubname> <trelloname> command that would be very helpful.

Priority for name search should be CU > GitHub > Trello.

Examples:
!whois csejb
> csejb is codecorsair on GitHub & JB (@codecorsair) on Trello.

!whois codecorsair
> codecorsair is csejb on CU & JB (@codecorsair) on Trello.

!whois mehuge
> Mehuge is mehuge on GitHub & Mehuge (@mehuge) on Trello.

**Comment by sysrage** [comment]
This is now mostly complete. Remaining items:
 - Allow adding users with missing GitHub or Trello usernames by specifying 'none'.
 - Finish !usermod command to modify existing users.

Finished:
 - !useradd command allows any CSE member or existing Mod Squad member to add new users.
 - !userdel command allows any CSE member or existing Mod Squad memeber to delete users.
 - !userlist command sends a PM with the full Mod Squad member list.
 - !whois command allows searching for an existing Mod Squad member.
 - Users on the member list are now considered bot admins. They can set MOTD messages, add users, delete users, and anything else requiring admin status. Don't abuse this!

**Comment by codecorsair** [comment]
Looking good so far!

**Comment by sysrage** [comment]
This feature is now complete and the README has been updated.
